name: Terraform Plan
on: [push]
jobs:
  Github-Stack:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.3.0-beta1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.STACKS_GITHUB__AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STACKS_GITHUB__AWS_SECRET_ACCESS_KEY }}
      - name: Plan Github Stack
        env:
          TF_VAR_github_token: ${{ secrets.STACKS_GITHUB__GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.STACKS_GITHUB__GITHUB_TOKEN }}
          TF_VAR_pipeline: "true"
          AWS_CONFIG_FILE: /__w/infrastructure/config
        run: |
          cd /__w/infrastructure/infrastructure/stacks/github
          terraform init -upgrade
          terraform plan -detailed-exitcode

